import type { Metadata } from "next";
import { Navbar, Footer} from "../components/index"
import {Providers} from "./providers";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="pl-[30px] ">
        <Providers>
        <Navbar />
        {children}
        <Footer />
        </Providers>
        </body>
    </html>
  );
}
